### ISSUE TITLE
constant OpenSSL::Cipher::Cipher is deprecated

### ISSUE THREAD

**Issue by snood1205** [chicks/aes#8] opened 2017-01-28 15:29 UTC
`OpenSSL::Cipher::Cipher` has been deprecated in favor of `OpenSSL::Cipher` per [this doc](https://ruby-doc.org/stdlib-2.4.0/libdoc/openssl/rdoc/OpenSSL/Cipher/Cipher.html).

**Comment by jalerson** [comment] 2017-06-01 17:40
I just fixed it in my fork: [https://github.com/jalerson/aes](https://github.com/jalerson/aes)

You just need to refer to my repository in your Gemfile:

`gem 'aes', git: 'https://github.com/jalerson/aes'`

**Comment by Ch4s3** [comment] 2017-12-05 04:27
Just as a heads up, this may break you implementation if you used a key or iv longer than 16 bytes https://github.com/ruby/ruby/commit/ce635262f53b760284d56bb1027baebaaec175d1

**Comment by dotanlang** [comment] 2019-04-22 11:47
Is this the solution?
Is there any official fix?
I'm having this problem after upgrading ruby to 2.5.3

**Comment by jcabasc** [comment] 2019-04-24 04:19
@dotanlang actually that repo no longer exists.

**Comment by matthias-g** [comment] 2019-11-08 09:39
The problem is fixed on the master branch: `gem 'aes', git: 'https://github.com/chicks/aes'`

**Comment by vanaltj** [comment] 2020-09-30 22:14
Sorry folks, I'd gotten maintainership last year intending to take care of this but then let it fall through the cracks. Now, 0.5.1 is finally released resolving this deprecation warning.

**Closed by vanaltj** 2020-09-30 22:14 UTC
